name: win-build
on:
  workflow_dispatch: {}
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    env:
      BUILD_TYPE: Release

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: 14.3

      - uses: jurplel/install-qt-action@v4
        with:
          version: '6.7.*'
          host: 'windows'
          arch: 'win64_msvc2022_64'
          cache: true

      - name: Install Ninja via choco
        run: choco install ninja --no-progress -y

      - name: Configure
        shell: pwsh
        run: >
          cmake -S . -B build -G "Ninja"
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
          -DCMAKE_PREFIX_PATH="$env:Qt6_DIR"

      - name: Build
        run: cmake --build build --parallel

      - name: Find built EXE
        id: findexe
        shell: pwsh
        run: |
          $exe = Get-ChildItem -Recurse -Path build -Filter "*.exe" |
                 Where-Object { $_.FullName -match "input-leap\.exe$" -or $_.Name -match "input" } |
                 Select-Object -First 1
          if (-not $exe) { throw "No EXE found under build/" }
          "exe=$($exe.FullName)" >> $env:GITHUB_OUTPUT
          Write-Host "EXE => $($exe.FullName)"

      - name: Deploy Qt runtime (windeployqt)
        shell: pwsh
        run: |
          & "$env:IQTA_TOOLS\bin\windeployqt.exe" "${{ steps.findexe.outputs.exe }}" --release --compiler-runtime

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: input-leap-windows
          path: build\
